---
- hosts: all
  user: root

  vars:
    - ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: "Include toyautomation host controller installation."
      include_tasks: install_toyautomation_host_controller_tasks.yml
